package com.example.YUmarket.model


enum class CellType {
    HOME_DETAIL_ITEM_CELL,
    HOME_MAIN_MARKET_CELL,
    HOME_MAIN_ITEM_CELL,
    HOME_TOWN_MARKET_CELL,
    HOME_ITEM_CELL,
    CUSTOMER_SERVICE_CELL,
    SUGGEST_CELL,
    LIKE_MARKET_CELL,
    LIKE_ITEM_CELL,
    MAP_ITEM_CELL
}